### ISSUE TITLE
passing variable in the shortlink

### ISSUE THREAD

**Issue by therealelyayo** [kremalicious/gatsby-redirect-from#24]
would it be possible to append ?email=jackson@be.com to these redirect and then using the domain of the email to redirect somewhere ,
example?email=t@gmail.com would goto gmail.com

and t@yahoo.com shuld got yahoo.com

would that be possible

**Comment by kremalicious** [comment]
hi there, not sure I understand your use case. What do you mean by `shortlink`?

I suppose you want to do:

```
redirect_from:
  - /page?email=jackson@be.com
```

And then have the current page you put that frontmatter on to redirect to the email domain?

This is kinda out-of-scope for this plugin since this would be a highly specific use case so I suggest you either fork this plugin or look for another solution.
